### ISSUE TITLE
Please clarify the copyright owner

### ISSUE THREAD

**Issue by igor-petruk** [mellite/colorful#24]
Hi,

I am working on packaging `colorful` for Debian. Debian requires to have a license and copyright to be clearly specified.

In this package copyright in the `license` file and in `Cargo.toml`: it is `da2018 <da2018t@gmail.com>` vs `Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)`.

Can you please clarify who is the copyright holder, or maybe it is both of these addresses?

Thanks,
Igor.

**Comment by bkda** [comment]
My bad, thanks for reminding me. This issue has been fixed.
